# Generated by Django 5.2.4 on 2025-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favourites',
            field=models.TextField(choices=[('FAVOURITES', 'Избранное'), ('NO FAVOURITES', 'Не избранное')], default='NO FAVOURITES'),
        ),
    ]
