# Generated by Django 5.2.4 on 2025-07-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='favourites',
            field=models.BooleanField(default=('NO FAVOURITES', 'Не избранное')),
        ),
    ]
