# Generated by Django 5.2.4 on 2025-07-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='favourites',
            field=models.TextField(choices=[('FAVOURITES', 'Избранное'), ('NO FAVOURITES', 'Не избранное')], default='NO FAVOURITES'),
        ),
    ]
